server:
  port: 8086
eureka:
  client:
    service-url:
      #注册中心地址 8080是你注册中心里面的端口号
      defaultZone: http://localhost:8080/eureka
spring:
  application:
    #服务在注册中心的名称 不同服务名称不能重复
    name: cloud-provider
  thymeleaf:
    cache: false
  spring:
    data:
      elasticsearch:
        repositories:
          enabled: true
        cluster-nodes: 127.0.0.1:9300
        cluster-name: my-application
